### ISSUE TITLE
Slight Problem with gap after ? in Ternary Operator

### ISSUE THREAD

**Issue by Arifursdev** [kokororin/vscode-phpfmt#145]
```php
// before format
$a = 1 === 1 ? 1 : 2; 

$c = $isTrue ? self::getAltText($id) : ''; 

$c = $isTrue ? static::getAltText($id) : ''; 
```

after format when static is used

```php
// after format
$a = 1 === 1 ? 1 : 2; ✅

$c = $isTrue ? self::getAltText( $id ) : '';  ✅

$c = $isTrue?static::getAltText( $id ) : '';  ❌
```

**Comment by driade** [comment]
Hi, good morning. Got it, I'll take a look.

**Comment by driade** [comment]
Hi @Arifursdev this should be fixed.

**Comment by Arifursdev** [comment]
@driade Thank you

**Comment by eltorjmen** [comment]
Sorry for reviving this issue but the problem is still present in this case 

`$result = true ? \Str::of('true') : \Str::of('false');`

after formatting it becomes

`$result = true?\Str::of('true') : \Str::of('false');`

the `\` causes the spacing to disappear, without it the line is formatted correctly

`$result = true ? Str::of('true') : \Str::of('false');`

**Comment by driade** [comment]
Hi again @eltorjmen , it's already fixed

https://github.com/driade/phpfmt8/commit/865663e82d183aaf2591456058037b4ef60327c0

**Comment by eltorjmen** [comment]
Thanks
