### ISSUE TITLE
Constant arrays on classes causes all keywords before `function` to be removed

### ISSUE THREAD

**Issue by wisaac407** [kokororin/vscode-phpfmt#42]
If you have a class with a constant on it that is an array, static functions will get re-written to not be static (also, the `public` keyword gets removed). E.g:

this
```php
<?php

class Bug {
    const BROKEN = array();

    public static function test() {

    }
}
```

Will get re-written into this:

```php
<?php

class Bug {
    const BROKEN = array();

    function test() {

    }
}

```

It seems to remove all keywords before the `function` keyword:

```php
<?php

class Bug {
    const BROKEN = array();

    private function test() {

    }
}
```

Will get re-written into this:

```php
<?php

class Bug {
    const BROKEN = array();

    function test() {

    }
}

```

However, this works:

```php
<?php

const WORKS = array();

class Bug {

    public static function test() {

    }
}
```

These are the settings I'm using:

```json
{
    "phpfmt.exclude": [
        "PSR2CurlyOpenNextLine",
    ],
    "phpfmt.passes": [
        "AlignDoubleArrow"
    ],
    "phpfmt.psr2": true
}
```

**Comment by yousufmj** [comment]
this is really annoying, only the first function stays  the same, any other function all keywords get removed. I have a const array and having the same issue

**Comment by josjojo** [comment]
I'm also having this issue. Is there a fix yet?

**Comment by loderunner** [comment]
Same here. Can we at least get the name of the transformation that does this so we can disable it?

**Comment by demolitions** [comment]
Almost a year passed, do we have any info on this issue?
Or is dropping phpfmt and using another formatter the only option?

**Comment by ianleeder** [comment]
I too found this bug the hard way.  However quick test indicates this is enough to disable it:
```json
{
    "phpfmt.exclude": [
        "PSR2ModifierVisibilityStaticOrder"
    ]
}
```

**Comment by vamaship-saud-qureshi** [comment]
Please add a permanent fix for it. It can screw up a perfectly working code in production.

**Comment by Christian-Rinne** [comment]
The bug still persists

**Comment by driade** [comment]
I'll take a look.

**Comment by driade** [comment]
There you're, it's fixed in the latest release.

**Comment by Christian-Rinne** [comment]
How do I get the update into my version that I use in VSCode? (phpfmt 1.1.9)

**Comment by Christian-Rinne** [comment]
I've done it, and it showed that it was successful, but unfortunately the bug still persists (I've also restarted VSCode).

**Comment by kokororin** [comment]
Please try version 1.1.10, it contains the latest fmt

**Comment by Christian-Rinne** [comment]
Thank you so much for your effort and help! I have just upgraded phpfmt to 1.1.10 and restarted VSCode, but the problem still persists. I also ran "phpfmt: Upgrade fmt.phar or fmt.stub.php" again (and restarted afterwards).

To help you track down the error, here are some data with which you might be able to reproduce the bug:

- As far as I know, it only occurs with functions named **print()** within classes.

Here are my VSCode settings.json:
```
{
  "settings": {
    "editor.accessibilitySupport": "off",
    "editor.bracketPairColorization.enabled": false,
    "editor.codeLens": false,
    "editor.fontFamily": "Menlo, SF Mono, JetBrains Mono, Source Code Pro, ProggyVector, serif",
    "editor.fontSize": 12.5,
    "editor.formatOnPaste": false,
    "editor.formatOnSave": true,
    "editor.formatOnType": false,
    "editor.insertSpaces": true,
    "editor.inlineSuggest.enabled": true,
    "editor.lineHeight": 1.7,
    "editor.mouseWheelScrollSensitivity": 0.2,
    "editor.tabSize": 4,
    "editor.renderWhitespace": "all"
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "[php]": {
      "editor.defaultFormatter": "kokororin.vscode-phpfmt",
      "editor.formatOnSave": true,
      "editor.formatOnType": false,
      "editor.formatOnPaste": false,
      "editor.tabSize": 4
    },
    "phpfmt.php_bin": "/usr/local/bin/php",
    "phpfmt.psr2": true,
    "phpfmt.passes": ["AllmanStyleBraces"],
    "phpfmt.enable_auto_align": true,
    "editor.tokenColorCustomizations": {
      "textMateRules": [...]
    },
    "explorer.compactFolders": false,
    "explorer.confirmDelete": false,
    "explorer.openEditors.visible": 0,
    "git.mergeEditor": true,
    "json.schemas": [],
    "workbench.colorCustomizations": {
      "editor.background": "#171c23",
      "editorIndentGuide.activeBackground": "#2e3846",
      "editorIndentGuide.background": "#1f262f"
    },
    "workbench.colorTheme": "One Dark Pro Darker",
    "workbench.editor.wrapTabs": true,
    "workbench.iconTheme": "vsc-jetbrains-icons-enhanced",
    "workbench.startupEditor": "none",
  }
}
```
when i add the following rule, the bug is gone:
```
"phpfmt.exclude": ["PSR2ModifierVisibilityStaticOrder"],
```

I hope you can find the bug. Thank you so far! If further data is needed, I'll be glad to provide it.

**Comment by driade** [comment]
Thanks, let me check with the sample given

**Comment by driade** [comment]
There you're, patched uploaded. Please try upgrading via "phpfmt: Upgrade fmt.phar or fmt.stub.php" and let's see.

**Comment by Christian-Rinne** [comment]
Yes! it works :) Thank you very much
